version: '3.0'

services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - '3200:3200'
      - '27017:27017'
    volumes:
    - .:/usr/src/api
    env_file:
      - .env
networks: 
  api:
    ipam:
      config:
        - subnet: 192.168.20.0/24